var data = [{"country":"Afghanistan","hburden_rank":"22:Afghanistan","hburden_rankn":22,"iso_numeric":4,"mr":1.322913,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Albania","hburden_rank":"","hburden_rankn":null,"iso_numeric":8,"mr":2.421308,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Algeria","hburden_rank":"","hburden_rankn":null,"iso_numeric":12,"mr":1.860676,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"American Samoa","hburden_rank":"","hburden_rankn":null,"iso_numeric":16,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Andorra","hburden_rank":"","hburden_rankn":null,"iso_numeric":20,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Angola","hburden_rank":"","hburden_rankn":null,"iso_numeric":24,"mr":3.284475,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Anguilla","hburden_rank":"","hburden_rankn":null,"iso_numeric":660,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Antigua and Barbuda","hburden_rank":"","hburden_rankn":null,"iso_numeric":28,"mr":33.33333,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Argentina","hburden_rank":"","hburden_rankn":null,"iso_numeric":32,"mr":4.536149,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Armenia","hburden_rank":"","hburden_rankn":null,"iso_numeric":51,"mr":3.833333,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Aruba","hburden_rank":"","hburden_rankn":null,"iso_numeric":533,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Australia","hburden_rank":"","hburden_rankn":null,"iso_numeric":36,"mr":3.846154,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Austria","hburden_rank":"","hburden_rankn":null,"iso_numeric":40,"mr":6.487696,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Azerbaijan","hburden_rank":"","hburden_rankn":null,"iso_numeric":31,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Bahamas","hburden_rank":"","hburden_rankn":null,"iso_numeric":44,"mr":17.5,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Bahrain","hburden_rank":"","hburden_rankn":null,"iso_numeric":48,"mr":2.666667,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Bangladesh","hburden_rank":"6:Bangladesh","hburden_rankn":6,"iso_numeric":50,"mr":3.913443,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Barbados","hburden_rank":"","hburden_rankn":null,"iso_numeric":52,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Belarus","hburden_rank":"","hburden_rankn":null,"iso_numeric":112,"mr":4.933009,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Belgium","hburden_rank":"","hburden_rankn":null,"iso_numeric":56,"mr":5.576679,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Belize","hburden_rank":"","hburden_rankn":null,"iso_numeric":84,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Benin","hburden_rank":"","hburden_rankn":null,"iso_numeric":204,"mr":6.322549,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Bermuda","hburden_rank":"","hburden_rankn":null,"iso_numeric":60,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Bhutan","hburden_rank":"","hburden_rankn":null,"iso_numeric":64,"mr":3.231292,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Bolivia (Plurinational State of)","hburden_rank":"","hburden_rankn":null,"iso_numeric":68,"mr":4.276961,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Bonaire, Saint Eustatius and Saba","hburden_rank":"","hburden_rankn":null,"iso_numeric":535,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Bosnia and Herzegovina","hburden_rank":"","hburden_rankn":null,"iso_numeric":70,"mr":4.920515,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Botswana","hburden_rank":"","hburden_rankn":null,"iso_numeric":72,"mr":9.734645,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Brazil","hburden_rank":"14:Brazil","hburden_rankn":14,"iso_numeric":76,"mr":7.268383,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"British Virgin Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":92,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Brunei Darussalam","hburden_rank":"","hburden_rankn":null,"iso_numeric":96,"mr":7.211538,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Bulgaria","hburden_rank":"","hburden_rankn":null,"iso_numeric":100,"mr":7.882241,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Burkina Faso","hburden_rank":"","hburden_rankn":null,"iso_numeric":854,"mr":11.5353,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Burundi","hburden_rank":"","hburden_rankn":null,"iso_numeric":108,"mr":6.95532,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Cabo Verde","hburden_rank":"","hburden_rankn":null,"iso_numeric":132,"mr":5.36193,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Cambodia","hburden_rank":"21:Cambodia","hburden_rankn":21,"iso_numeric":116,"mr":2.26738,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Cameroon","hburden_rank":"","hburden_rankn":null,"iso_numeric":120,"mr":7.675261,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Canada","hburden_rank":"","hburden_rankn":null,"iso_numeric":124,"mr":7.147674,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Cayman Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":136,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Central African Republic","hburden_rank":"","hburden_rankn":null,"iso_numeric":140,"mr":6.030727,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Chad","hburden_rank":"","hburden_rankn":null,"iso_numeric":148,"mr":4.550956,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Chile","hburden_rank":"","hburden_rankn":null,"iso_numeric":152,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"China","hburden_rank":"2:China","hburden_rankn":2,"iso_numeric":156,"mr":0.947237,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"China, Hong Kong SAR","hburden_rank":"","hburden_rankn":null,"iso_numeric":344,"mr":16.67818,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"China, Macao SAR","hburden_rank":"","hburden_rankn":null,"iso_numeric":446,"mr":4.075235,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Colombia","hburden_rank":"","hburden_rankn":null,"iso_numeric":170,"mr":8.885002,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Comoros","hburden_rank":"","hburden_rankn":null,"iso_numeric":174,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Congo","hburden_rank":"","hburden_rankn":null,"iso_numeric":178,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Cook Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":184,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Costa Rica","hburden_rank":"","hburden_rankn":null,"iso_numeric":188,"mr":8.333333,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"CÃ´te d'Ivoire","hburden_rank":"","hburden_rankn":null,"iso_numeric":384,"mr":8.867248,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Croatia","hburden_rank":"","hburden_rankn":null,"iso_numeric":191,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Cuba","hburden_rank":"","hburden_rankn":null,"iso_numeric":192,"mr":8.613729,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"CuraÃ§ao","hburden_rank":"","hburden_rankn":null,"iso_numeric":531,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Cyprus","hburden_rank":"","hburden_rankn":null,"iso_numeric":196,"mr":9.090909,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Czech Republic","hburden_rank":"","hburden_rankn":null,"iso_numeric":203,"mr":17.13287,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Democratic People's Republic of Korea","hburden_rank":"","hburden_rankn":null,"iso_numeric":408,"mr":2.383012,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Democratic Republic of the Congo","hburden_rank":"10:Democratic Republic of Congo","hburden_rankn":10,"iso_numeric":180,"mr":3.772948,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Denmark","hburden_rank":"","hburden_rankn":null,"iso_numeric":208,"mr":4.797048,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Djibouti","hburden_rank":"","hburden_rankn":null,"iso_numeric":262,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Dominica","hburden_rank":"","hburden_rankn":null,"iso_numeric":212,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Dominican Republic","hburden_rank":"","hburden_rankn":null,"iso_numeric":214,"mr":4.360228,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Ecuador","hburden_rank":"","hburden_rankn":null,"iso_numeric":218,"mr":4.582096,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Egypt","hburden_rank":"","hburden_rankn":null,"iso_numeric":818,"mr":2.860452,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"El Salvador","hburden_rank":"","hburden_rankn":null,"iso_numeric":222,"mr":5.016358,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Equatorial Guinea","hburden_rank":"","hburden_rankn":null,"iso_numeric":226,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Eritrea","hburden_rank":"","hburden_rankn":null,"iso_numeric":232,"mr":5.717256,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Estonia","hburden_rank":"","hburden_rankn":null,"iso_numeric":233,"mr":10.90226,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Ethiopia","hburden_rank":"7:Ethiopia","hburden_rankn":7,"iso_numeric":231,"mr":2.821624,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Fiji","hburden_rank":"","hburden_rankn":null,"iso_numeric":242,"mr":4.694836,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Finland","hburden_rank":"","hburden_rankn":null,"iso_numeric":246,"mr":11.5016,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"France","hburden_rank":"","hburden_rankn":null,"iso_numeric":250,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"French Polynesia","hburden_rank":"","hburden_rankn":null,"iso_numeric":258,"mr":5.172414,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Gabon","hburden_rank":"","hburden_rankn":null,"iso_numeric":266,"mr":1.940828,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Gambia","hburden_rank":"","hburden_rankn":null,"iso_numeric":270,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Georgia","hburden_rank":"","hburden_rankn":null,"iso_numeric":268,"mr":2.194949,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Germany","hburden_rank":"","hburden_rankn":null,"iso_numeric":276,"mr":9.796473,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Ghana","hburden_rank":"","hburden_rankn":null,"iso_numeric":288,"mr":9.518402,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Greece","hburden_rank":"","hburden_rankn":null,"iso_numeric":300,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Greenland","hburden_rank":"","hburden_rankn":null,"iso_numeric":304,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Grenada","hburden_rank":"","hburden_rankn":null,"iso_numeric":308,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Guam","hburden_rank":"","hburden_rankn":null,"iso_numeric":316,"mr":7.692307,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Guatemala","hburden_rank":"","hburden_rankn":null,"iso_numeric":320,"mr":5.841293,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Guinea","hburden_rank":"","hburden_rankn":null,"iso_numeric":324,"mr":4.580411,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Guinea-Bissau","hburden_rank":"","hburden_rankn":null,"iso_numeric":624,"mr":7.374631,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Guyana","hburden_rank":"","hburden_rankn":null,"iso_numeric":328,"mr":12.15227,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Haiti","hburden_rank":"","hburden_rankn":null,"iso_numeric":332,"mr":4.961112,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Honduras","hburden_rank":"","hburden_rankn":null,"iso_numeric":340,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Hungary","hburden_rank":"","hburden_rankn":null,"iso_numeric":348,"mr":10.35889,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Iceland","hburden_rank":"","hburden_rankn":null,"iso_numeric":352,"mr":11.11111,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"India","hburden_rank":"1:India","hburden_rankn":1,"iso_numeric":356,"mr":3.53422,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Indonesia","hburden_rank":"3:Indonesia","hburden_rankn":3,"iso_numeric":360,"mr":2.299737,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Iran (Islamic Republic of)","hburden_rank":"","hburden_rankn":null,"iso_numeric":364,"mr":7.8279,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Iraq","hburden_rank":"","hburden_rankn":null,"iso_numeric":368,"mr":3.113575,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Ireland","hburden_rank":"","hburden_rankn":null,"iso_numeric":372,"mr":3.761755,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Israel","hburden_rank":"","hburden_rankn":null,"iso_numeric":376,"mr":7.782101,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Italy","hburden_rank":"","hburden_rankn":null,"iso_numeric":380,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Jamaica","hburden_rank":"","hburden_rankn":null,"iso_numeric":388,"mr":15.59633,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Japan","hburden_rank":"","hburden_rankn":null,"iso_numeric":392,"mr":15.73901,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Jordan","hburden_rank":"","hburden_rankn":null,"iso_numeric":400,"mr":1.923077,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Kazakhstan","hburden_rank":"","hburden_rankn":null,"iso_numeric":398,"mr":2.266129,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Kenya","hburden_rank":"13:Kenya","hburden_rankn":13,"iso_numeric":404,"mr":4.865384,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Kiribati","hburden_rank":"","hburden_rankn":null,"iso_numeric":296,"mr":6.567164,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Kuwait","hburden_rank":"","hburden_rankn":null,"iso_numeric":414,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Kyrgyzstan","hburden_rank":"","hburden_rankn":null,"iso_numeric":417,"mr":2.812671,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Lao People's Democratic Republic","hburden_rank":"","hburden_rankn":null,"iso_numeric":418,"mr":0.4110251,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Latvia","hburden_rank":"","hburden_rankn":null,"iso_numeric":428,"mr":9.090909,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Lebanon","hburden_rank":"","hburden_rankn":null,"iso_numeric":422,"mr":1.010101,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Lesotho","hburden_rank":"","hburden_rankn":null,"iso_numeric":426,"mr":13.18415,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Liberia","hburden_rank":"","hburden_rankn":null,"iso_numeric":430,"mr":3.2831,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Libya","hburden_rank":"","hburden_rankn":null,"iso_numeric":434,"mr":1.134846,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Lithuania","hburden_rank":"","hburden_rankn":null,"iso_numeric":440,"mr":9.5114,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Luxembourg","hburden_rank":"","hburden_rankn":null,"iso_numeric":442,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Madagascar","hburden_rank":"","hburden_rankn":null,"iso_numeric":450,"mr":4.896745,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Malawi","hburden_rank":"","hburden_rankn":null,"iso_numeric":454,"mr":10.72727,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Malaysia","hburden_rank":"","hburden_rankn":null,"iso_numeric":458,"mr":9.360553,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Maldives","hburden_rank":"","hburden_rankn":null,"iso_numeric":462,"mr":4.494382,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Mali","hburden_rank":"","hburden_rankn":null,"iso_numeric":466,"mr":7.178218,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Malta","hburden_rank":"","hburden_rankn":null,"iso_numeric":470,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Marshall Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":584,"mr":7.633588,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Mauritania","hburden_rank":"","hburden_rankn":null,"iso_numeric":478,"mr":2.64167,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Mauritius","hburden_rank":"","hburden_rankn":null,"iso_numeric":480,"mr":4.504505,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Mexico","hburden_rank":"","hburden_rankn":null,"iso_numeric":484,"mr":7.756005,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Micronesia (Federated States of)","hburden_rank":"","hburden_rankn":null,"iso_numeric":583,"mr":2.941176,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Monaco","hburden_rank":"","hburden_rankn":null,"iso_numeric":492,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Mongolia","hburden_rank":"","hburden_rankn":null,"iso_numeric":496,"mr":1.907152,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Montenegro","hburden_rank":"","hburden_rankn":null,"iso_numeric":499,"mr":9,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Montserrat","hburden_rank":"","hburden_rankn":null,"iso_numeric":500,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Morocco","hburden_rank":"","hburden_rankn":null,"iso_numeric":504,"mr":1.757521,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Mozambique","hburden_rank":"19:Mozambique* missing 2011 outcome data","hburden_rankn":19,"iso_numeric":508,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Myanmar","hburden_rank":"20:Myanmar","hburden_rankn":20,"iso_numeric":104,"mr":4.386938,"stgy1":1,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Namibia","hburden_rank":"","hburden_rankn":null,"iso_numeric":516,"mr":6.640176,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Nauru","hburden_rank":"","hburden_rankn":null,"iso_numeric":520,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Nepal","hburden_rank":"","hburden_rankn":null,"iso_numeric":524,"mr":3.00815,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Netherlands","hburden_rank":"","hburden_rankn":null,"iso_numeric":528,"mr":3.703704,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"New Caledonia","hburden_rank":"","hburden_rankn":null,"iso_numeric":540,"mr":11.53846,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"New Zealand","hburden_rank":"","hburden_rankn":null,"iso_numeric":554,"mr":6.857143,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Nicaragua","hburden_rank":"","hburden_rankn":null,"iso_numeric":558,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Niger","hburden_rank":"","hburden_rankn":null,"iso_numeric":562,"mr":4.795737,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Nigeria","hburden_rank":"4:Nigeria","hburden_rankn":4,"iso_numeric":566,"mr":6.012129,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Niue","hburden_rank":"","hburden_rankn":null,"iso_numeric":570,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Northern Mariana Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":580,"mr":5.405406,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Norway","hburden_rank":"","hburden_rankn":null,"iso_numeric":578,"mr":2.735562,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Oman","hburden_rank":"","hburden_rankn":null,"iso_numeric":512,"mr":1.912568,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Pakistan","hburden_rank":"8:Pakistan","hburden_rankn":8,"iso_numeric":586,"mr":1.53456,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Palau","hburden_rank":"","hburden_rankn":null,"iso_numeric":585,"mr":12.5,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Panama","hburden_rank":"","hburden_rankn":null,"iso_numeric":591,"mr":7.882736,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Papua New Guinea","hburden_rank":"","hburden_rankn":null,"iso_numeric":598,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Paraguay","hburden_rank":"","hburden_rankn":null,"iso_numeric":600,"mr":7.754137,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Peru","hburden_rank":"","hburden_rankn":null,"iso_numeric":604,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Philippines","hburden_rank":"9:Philippines","hburden_rankn":9,"iso_numeric":608,"mr":1.955194,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Poland","hburden_rank":"","hburden_rankn":null,"iso_numeric":616,"mr":7.569721,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Portugal","hburden_rank":"","hburden_rankn":null,"iso_numeric":620,"mr":5.110384,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Puerto Rico","hburden_rank":"","hburden_rankn":null,"iso_numeric":630,"mr":26,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Qatar","hburden_rank":"","hburden_rankn":null,"iso_numeric":634,"mr":0.1956947,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Republic of Korea","hburden_rank":"","hburden_rankn":null,"iso_numeric":410,"mr":0.6276619,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Republic of Moldova","hburden_rank":"","hburden_rankn":null,"iso_numeric":498,"mr":8.081335,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Romania","hburden_rank":"","hburden_rankn":null,"iso_numeric":642,"mr":6.099802,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Russian Federation","hburden_rank":"11:Russian Federation","hburden_rankn":11,"iso_numeric":643,"mr":7.142535,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Rwanda","hburden_rank":"","hburden_rankn":null,"iso_numeric":646,"mr":9.230769,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Saint Kitts and Nevis","hburden_rank":"","hburden_rankn":null,"iso_numeric":659,"mr":0,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Saint Lucia","hburden_rank":"","hburden_rankn":null,"iso_numeric":662,"mr":14.28571,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Saint Vincent and the Grenadines","hburden_rank":"","hburden_rankn":null,"iso_numeric":670,"mr":23.52941,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Samoa","hburden_rank":"","hburden_rankn":null,"iso_numeric":882,"mr":11.11111,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"San Marino","hburden_rank":"","hburden_rankn":null,"iso_numeric":674,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Sao Tome and Principe","hburden_rank":"","hburden_rankn":null,"iso_numeric":678,"mr":6.862745,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Saudi Arabia","hburden_rank":"","hburden_rankn":null,"iso_numeric":682,"mr":5.196484,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Senegal","hburden_rank":"","hburden_rankn":null,"iso_numeric":686,"mr":5.00466,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Serbia","hburden_rank":"","hburden_rankn":null,"iso_numeric":688,"mr":6.911929,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Seychelles","hburden_rank":"","hburden_rankn":null,"iso_numeric":690,"mr":8.695652,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Sierra Leone","hburden_rank":"","hburden_rankn":null,"iso_numeric":694,"mr":3.6452,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Singapore","hburden_rank":"","hburden_rankn":null,"iso_numeric":702,"mr":13.16656,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Sint Maarten (Dutch part)","hburden_rank":"","hburden_rankn":null,"iso_numeric":534,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Slovakia","hburden_rank":"","hburden_rankn":null,"iso_numeric":703,"mr":4.878049,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Slovenia","hburden_rank":"","hburden_rankn":null,"iso_numeric":705,"mr":17.58242,"stgy1":1,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Solomon Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":90,"mr":3.291139,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Somalia","hburden_rank":"","hburden_rankn":null,"iso_numeric":706,"mr":4.255131,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"South Africa","hburden_rank":"5:South Africa","hburden_rankn":5,"iso_numeric":710,"mr":7.796253,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"South Sudan","hburden_rank":"","hburden_rankn":null,"iso_numeric":728,"mr":3.681761,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Spain","hburden_rank":"","hburden_rankn":null,"iso_numeric":724,"mr":7.057511,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Sri Lanka","hburden_rank":"","hburden_rankn":null,"iso_numeric":144,"mr":5.00631,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Sudan","hburden_rank":"","hburden_rankn":null,"iso_numeric":729,"mr":2.178579,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Suriname","hburden_rank":"","hburden_rankn":null,"iso_numeric":740,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Swaziland","hburden_rank":"","hburden_rankn":null,"iso_numeric":748,"mr":12.1936,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Sweden","hburden_rank":"","hburden_rankn":null,"iso_numeric":752,"mr":2.976191,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Switzerland","hburden_rank":"","hburden_rankn":null,"iso_numeric":756,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Syrian Arab Republic","hburden_rank":"","hburden_rankn":null,"iso_numeric":760,"mr":2.703515,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Tajikistan","hburden_rank":"","hburden_rankn":null,"iso_numeric":762,"mr":3.875316,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Thailand","hburden_rank":"18:Thailand","hburden_rankn":18,"iso_numeric":764,"mr":7.150576,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"The Former Yugoslav Republic of Macedonia","hburden_rank":"","hburden_rankn":null,"iso_numeric":807,"mr":6.514658,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Timor-Leste","hburden_rank":"","hburden_rankn":null,"iso_numeric":626,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Togo","hburden_rank":"","hburden_rankn":null,"iso_numeric":768,"mr":7.009174,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Tokelau","hburden_rank":"","hburden_rankn":null,"iso_numeric":772,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Tonga","hburden_rank":"","hburden_rankn":null,"iso_numeric":776,"mr":0,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Trinidad and Tobago","hburden_rank":"","hburden_rankn":null,"iso_numeric":780,"mr":11.98157,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Tunisia","hburden_rank":"","hburden_rankn":null,"iso_numeric":788,"mr":1.754978,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Turkey","hburden_rank":"","hburden_rankn":null,"iso_numeric":792,"mr":2.940973,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Turkmenistan","hburden_rank":"","hburden_rankn":null,"iso_numeric":795,"mr":4.018692,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Turks and Caicos Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":796,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Tuvalu","hburden_rank":"","hburden_rankn":null,"iso_numeric":798,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Uganda","hburden_rank":"16:Uganda","hburden_rankn":16,"iso_numeric":800,"mr":6.560019,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Ukraine","hburden_rank":"","hburden_rankn":null,"iso_numeric":804,"mr":9.790235,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"United Arab Emirates","hburden_rank":"","hburden_rankn":null,"iso_numeric":784,"mr":3.960396,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"United Kingdom of Great Britain and Northern Ireland","hburden_rank":"","hburden_rankn":null,"iso_numeric":826,"mr":4.195216,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"United Republic of Tanzania","hburden_rank":"15:United Republic of Tanzania","hburden_rankn":15,"iso_numeric":834,"mr":5.743105,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"United States of America","hburden_rank":"","hburden_rankn":null,"iso_numeric":840,"mr":4.882232,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Uruguay","hburden_rank":"","hburden_rankn":null,"iso_numeric":858,"mr":8.507854,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"US Virgin Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":850,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"Uzbekistan","hburden_rank":"","hburden_rankn":null,"iso_numeric":860,"mr":4.551626,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Vanuatu","hburden_rank":"","hburden_rankn":null,"iso_numeric":548,"mr":6.422019,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Venezuela (Bolivarian Republic of)","hburden_rank":"","hburden_rankn":null,"iso_numeric":862,"mr":5.882353,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Viet Nam","hburden_rank":"12:Viet Nam","hburden_rankn":12,"iso_numeric":704,"mr":2.542544,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Wallis and Futuna Islands","hburden_rank":"","hburden_rankn":null,"iso_numeric":876,"mr":null,"stgy1":null,"stgy2":null,"stgy3":null,"stgy4":null,"stgy5":null,"stgy6":null},
{"country":"West Bank and Gaza Strip","hburden_rank":"","hburden_rankn":null,"iso_numeric":275,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Yemen","hburden_rank":"","hburden_rankn":null,"iso_numeric":887,"mr":2.604411,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":0,"stgy5":null,"stgy6":null},
{"country":"Zambia","hburden_rank":"","hburden_rankn":null,"iso_numeric":894,"mr":null,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null},
{"country":"Zimbabwe","hburden_rank":"17:Zimbabwe","hburden_rankn":17,"iso_numeric":716,"mr":9.705815,"stgy1":null,"stgy2":null,"stgy3":0,"stgy4":1,"stgy5":null,"stgy6":null}]